name: Update Translations

on:
  push:
    paths:
      - 'masa-mods-chinese/zh_cn/**'
      - 'masa-mods-chinese/zh_tw/**'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with: 
            upload_sources: false
            upload_translations: true
        env:
            CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
            CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        
    